name: product_listing
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  dio: ^5.1.1
  beamer: ^1.5.3
  shimmer: ^2.0.0
  equatable: ^2.0.5
  flutter_dotenv: ^5.0.2
  bloc_concurrency: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.22.0
  bloc_test: ^9.1.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - .env

